name: chatapp_firebase
description: A new Flutter project.
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  lottie: ^2.3.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true
  
flutter_native_splash:
  color: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/
  