// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0keiedBnrfLsteK_gN0uYbIkd5pDhNxY',
    appId: '1:163481335334:web:6cf5dea8d0c0590448d8e7',
    messagingSenderId: '163481335334',
    projectId: 'chatapp-e5ec6',
    authDomain: 'chatapp-e5ec6.firebaseapp.com',
    storageBucket: 'chatapp-e5ec6.appspot.com',
    measurementId: 'G-MLMD82T0GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApX2yDmWyT7I5ApmyJTrR3CT7aeJ74Cs',
    appId: '1:163481335334:android:be7f50894f21967a48d8e7',
    messagingSenderId: '163481335334',
    projectId: 'chatapp-e5ec6',
    storageBucket: 'chatapp-e5ec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhYwqR7TBD0RqUpfgcqdhAyuiodQK_F0',
    appId: '1:163481335334:ios:cbd12b885270096b48d8e7',
    messagingSenderId: '163481335334',
    projectId: 'chatapp-e5ec6',
    storageBucket: 'chatapp-e5ec6.appspot.com',
    iosClientId: '163481335334-oum217vokmum261gbfn49nlic4nhe12g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
